version: "3.9"

services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # Mount the entire project directory to the container
      - /usr/src/app/node_modules # Exclude `node_modules` to prevent conflicts
    environment:
      CHOKIDAR_USEPOLLING: "true" # Enable polling for file watching
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "textsDb"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
